sudo: enabled

language: cpp

before_install:
  - export CURRENT_PROJ_DIR=$(pwd)
  - mkdir gtest
  - cd gtest
  - git clone https://github.com/google/googletest.git
  - cd googletest/googletest
  - export GTEST_DIR=$(pwd)
  - cmake ${GTEST_DIR}
  - cd ${CURRENT_PROJ_DIR}
  - pip install --user cpp-coveralls

script:
  - make clean
  - make
  - ./PiezasTest

after_success:
  - coveralls --exclude *Test.cpp --exclude gtest/ --gcov-options '\-lpbc'
